# Docker compose for local development

version: '3.4'

services:
     
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=leotarla
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    hostname: postgres

  monolith:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./services:/home/root/monolith/services/
    ports:
      - '80:80'
    depends_on:
      - postgres
    hostname: monolith

  appointments:
    build:
      context: .
      dockerfile: Dockerfile.appointments
    ports:
      - '5001:5001'
    volumes:
      - ./appointments:/home/root/app/appointments/
    depends_on:
      - postgres
    hostname: appointments

volumes:
  postgres: