apiVersion: v1
kind: Service
metadata:
  name: monolith-app
  namespace: t20med
spec:
  selector:
    app: monolith-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: "NodePort"