"""Change date and time types

Revision ID: 3fd7d427e57c
Revises: f72916feede8
Create Date: 2022-09-09 14:52:42.271897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd7d427e57c'
down_revision = 'f72916feede8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda','date')
    op.drop_column('agenda','time')
    op.add_column('agenda',sa.Column('date',sa.Date()))
    op.add_column('agenda',sa.Column('time',sa.Time()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agenda','date')
    op.drop_column('agenda','time')
    op.add_column('agenda',sa.Column('date',sa.String()))
    op.add_column('agenda',sa.Column('time',sa.String()))
    # ### end Alembic commands ###
