"""Doctor approved flag

Revision ID: 7342fa089ebd
Revises: 9172f6a27995
Create Date: 2022-09-08 12:14:50.501771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7342fa089ebd'
down_revision = '9172f6a27995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('doctors', sa.Column('banned', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'banned')
    op.drop_column('doctors', 'banned')
    op.drop_column('doctors', 'approved')
    # ### end Alembic commands ###
