"""Doctor specialties

Revision ID: f72916feede8
Revises: 7342fa089ebd
Create Date: 2022-09-09 11:34:42.260365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72916feede8'
down_revision = '7342fa089ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        INSERT INTO specialties (name, price) VALUES
        ('Alergia e Imunologia',100.0),
        ('Cardiologia',100.0),
        ('Clínico Geral',100.0),
        ('Dermatologia',100.0),
        ('Endocrinologia',100.0),
        ('Geriatria',100.0),
        ('Ginecologia',100.0),
        ('Homeopatia',100.0),
        ('Nutricionista',100.0),
        ('Pediatria',100.0),
        ('Psicologia',100.0),
        ('Psiquiatria',100.0);
        '''
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        DELETE from specialties
        '''
    )
    # ### end Alembic commands ###
