apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  namespace: t20med
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "leotarla"